### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by 0pcom** [seletskiy/go-makepkg#18]
[user@host01 seletskiy]$ go-makepkg -B "go-makepkg tool" git://github.com/seletskiy/go-makepkg.git
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.main()
	/tmp/pamac-build-user/go-makepkg/src/.go/src/go-makepkg/main.go:125 +0x1941

**Comment by seletskiy** [comment]
@0pcom: try `go get -u` first. I can't reproduce the problem.

**Comment by 0pcom** [comment]
Also- when I tried to install go-makepkg-git from the AUR it fails with 
==> ERROR: Unknown download protocol: ssh

go-makepkg installs successfully

**Comment by seletskiy** [comment]
@0pcom: OK, I found the problem. **You need to run `go get` in `go-makepkg` source directory to get fix.**

The thing is that you need to specify your name and e-mail in git config using following commands:

```
git config --global user.name '<YOUR NAME>'
git config --global user.email '<YOUR EMAIL>'
```

Those commands are required to correctly add `# Maintainer: <YOUR NAME> <YOUR EMAIL>` in the beginning of the PKGBUILD file. You also can specify values directly (without `git config`) by using `-m` flag.

**Comment by 0pcom** [comment]
Hmm its trying to find go-makepkg in /bin/go-makepkg since I uninstalled it, and doesn't seem to want to work when I go get your repo.

I will try it again after I reinstall it via the package manager

**Comment by 0pcom** [comment]
I renamed the file from gz-c.asc to gz-c and now instead of "source file not found" it just says "failed"

**Comment by seletskiy** [comment]
@0pcom: well, skycoin project doesn't seem to be go-gettable since it requires use of `dep` tool. `go-makepkg` is suitable only for creating PKGBUILDs only for repositories that work out of the box right after `go get`.

Therefore, you need to run `go-makepkg` without `-B` flag (no build), cd to `build` directory and modify PKGBUILD by yourself. Consult skycoin project README to see how to build it properly and which files you need to include in the package.
